#!/usr/bin/env php
<?php
/**************************************************************************
Copyright 2017 Benato Denis

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*****************************************************************************/

define('CLI_TOOLKIT', true);

global $argv;
global $argc;

//include the base application and perform basic operations
if (!file_exists(__DIR__.'/../../autoload.php'))
    die("You have to run 'composer install' to complete the installation!\n");
require __DIR__.'/../../autoload.php';


use Gishiki\Gishiki;
use Gishiki\Core\Environment;
use Gishiki\CLI\Console;
use Gishiki\CLI\ConsoleColor;
use GishikiCLI\CLIActions;

Gishiki::initialize();

if ($argc <= 1) {
    CLIActions::unspecified($argv[0]);
    exit(-1);
}

switch ($argv[1]) {
    case 'new-controller':
        if ($argc <= 2) {
            CLIActions::unspecified($argv[0]);
            exit(-1);
        }

        $controllerName = (isset($argv[2])) ? $argv[2] : '';
        CLIActions::createController($controllerName);
        break;

    case 'init':
        CLIActions::initialize();
        break;

    case 'help':
        CLIActions::help($argv[0]);
        nreak;

    default:
        CLIActions::unspecified($argv[0]);
        break;
}
